version: '3'

services:
  #Main shop_app
  core:
    image: lynxire/shop_main:0.4
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 1111
      DB_HOST: jdbc:postgresql://db/shopapp
      REDIS_HOST: redis
      REDIS_PORTS: 6379
  #Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - 5433:5433
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shopapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
  #Kafka
  kafka:
    image: apache/kafka:3.7.0
    ports:
      - 9092:9092
    depends_on:
      - core

  #ShomComments
  comments-service:
    image: lynxire/shop_comments:latest
    container_name: comments
    ports:
      - 8082:8082
    depends_on:
      - kafka
      - db_comments
    environment:
      COMPOSE_KAFKA_SERVERS: kafka:9092
      DB_USERNAME: postgres
      DB_PASSWORD: 1111
      DB_HOST: jdbc:postgresql://db_comments/comments

  db_comments:
    image: postgres:latest
    container_name: db-comments
    ports:
      - 5432:5432
    volumes:
      - ./comments_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111

  #ShopEmail
  email-service:
    image: lynxire/shop_email:latest
    container_name: email
    ports:
      - 8083:8083
    depends_on:
      - comments-service
    environment:
      COMPOSE_KAFKA_SERVERS: kafka:9092



volumes:
  postgres_data:
  comments_data:

