version: '3'

services:
  core:
    image: lynxire/shop_main:0.4
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 1111
      DB_HOST: jdbc:postgresql://db/shopapp
      REDIS_HOST: redis
      REDIS_PORTS: 6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
        - 5433:5433
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: shopapp
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1111
volumes:
  postgres_data: